export type Platform = 'web' | 'desktop' | 'tablet' | 'extension' | 'pro_mobile_ios' | 'twa' | string;
export type Currency = string;
export type FiatCategory = any;
export type FiatCategoryItemsInner = any;
export type FiatCategoryItemsInnerActionButton = any;
export type FiatCategoryItemsInnerInfoButtonsInner = any;
export type GetFiatMethods200ResponseData = any;
export type GetFiatMethods200ResponseDataLayoutByCountryInner = any;
export type GetPopularApps200ResponseData = any;
export type MyIp200Response = any;
export type PopularApp = any;
export type PopularCategory = any;
export type ChainName = string;
export type CheckForUpdatesGet200Response = any;
export type GetAllKeys200Response = any;
export type GetCurrencies200Response = any;
export type GetFiatMethods200Response = any;
export type GetNotifications200Response = any;
export type GetPopularApps200Response = any;
export type GetStakingEthenaMethods200Response = any;
export type GetStoriesBatch200Response = any;
export type GetSellRatesWidget200Response = any;
export type GetBuyRatesWidget200Response = any;
export type StoryInfo = any;
export type PingReadyGet500Response = any;

const passThrough = (json: any) => json;

export const GetStakingEthenaMethods200ResponseFromJSON = passThrough;
export const GetStakingEthenaMethods200ResponseToJSON = passThrough;
export const PingReadyGet500ResponseFromJSON = passThrough;
export const PingReadyGet500ResponseToJSON = passThrough;

export const GetStoriesBatch200ResponseFromJSON = passThrough;
export const GetStoriesBatch200ResponseToJSON = passThrough;
export const StoryInfoFromJSON = passThrough;
export const StoryInfoToJSON = passThrough;

export const GetSellRatesWidget200ResponseFromJSON = passThrough;
export const GetSellRatesWidget200ResponseToJSON = passThrough;
export const GetBuyRatesWidget200ResponseFromJSON = passThrough;
export const GetBuyRatesWidget200ResponseToJSON = passThrough;

export const ChainNameFromJSON = passThrough;
export const ChainNameToJSON = passThrough;
export const CheckForUpdatesGet200ResponseFromJSON = passThrough;
export const CheckForUpdatesGet200ResponseToJSON = passThrough;
export const GetAllKeys200ResponseFromJSON = passThrough;
export const GetAllKeys200ResponseToJSON = passThrough;
export const GetCurrencies200ResponseFromJSON = passThrough;
export const GetCurrencies200ResponseToJSON = passThrough;
export const GetFiatMethods200ResponseFromJSON = passThrough;
export const GetFiatMethods200ResponseToJSON = passThrough;
export const GetNotifications200ResponseFromJSON = passThrough;
export const GetNotifications200ResponseToJSON = passThrough;
export const GetPopularApps200ResponseFromJSON = passThrough;
export const GetPopularApps200ResponseToJSON = passThrough;
export const MyIp200ResponseFromJSON = passThrough;
export const MyIp200ResponseToJSON = passThrough;
export const PlatformFromJSON = passThrough;
export const PlatformToJSON = passThrough;
